global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

scrape_configs:
  # APISIX Gateway metrics
  - job_name: 'apisix'
    static_configs:
      - targets: ['apisix:9091']
    scrape_interval: 15s
    metrics_path: /apisix/prometheus/metrics

  # RSS Service metrics (if implementing custom metrics)
  - job_name: 'rss-service'
    static_configs:
      - targets: ['rss-service:3000']
    scrape_interval: 30s
    metrics_path: /api/metrics
    scrape_timeout: 10s

  # Prometheus itself
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # Node Exporter for system metrics (optional)
  - job_name: 'node'
    static_configs:
      - targets: ['node-exporter:9100']
